# Generated by Django 5.2.9 on 2025-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='n_instrument',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
