# Generated by Django 5.2.9 on 2025-12-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_instruments_n_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_study', models.CharField(max_length=50)),
                ('t_study', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('humeda', 'húmeda'), ('seca', 'seca'), ('fria', 'fría'), ('calida', 'cálida'), ('transicion', 'transición')], max_length=20)),
                ('n_specialist', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Peru', 'Perú')], max_length=10)),
                ('taxon', models.CharField(choices=[('plantas', 'Plantas'), ('mamiferos', 'Mamíferos'), ('aves', 'Aves'), ('anfibios', 'Anfibios'), ('reptiles', 'Reptiles')], max_length=20)),
                ('field', models.FileField(upload_to='studies/')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.instruments')),
            ],
        ),
    ]
