# Generated by Django 5.2.9 on 2025-12-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='field',
            field=models.FileField(blank=True, null=True, upload_to='studies/'),
        ),
    ]
