# Generated by Django 5.2.9 on 2025-12-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_study_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
